spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catdemo?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: SS!123456
  # elasticsearch配置
  elasticsearch:
    # 自定义属性---设置是否开启ES,false表不开窍ES
    open: true
    # es集群名称,如果下载es设置了集群名称,则使用配置的集群名称
    clusterName: es
    hosts: 127.0.0.1:9200
    # es 请求方式
    scheme: http
    # es 连接超时时间
    connectTimeOut: 1000
    # es socket 连接超时时间
    socketTimeOut: 30000
    # es 请求超时时间
    connectionRequestTimeOut: 500
    # es 最大连接数
    maxConnectNum: 100
    # es 每个路由的最大连接数
    maxConnectNumPerRoute: 100

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000
      database: 15

mybatis:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl


# PageHelper 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
